### ISSUE TITLE
Configuring logging output

### ISSUE THREAD

**Issue by fhieber** [awslabs/mxboard#10]
Is it possible to configure the logger of mxboard? If one uses frequent statements as such
```
with SummarWriter(logdir=.) as sw:
  sw.add_scalar()
```
the log of the application becomes quite cluttered with outputs like:
```
[INFO:root] Successfully opened events file: events.out.tfevents.1522834055.186590d665ad.ant.amazon.com
[INFO:root] Wrote 1 event to disk
[INFO:root] Wrote 1 event to disk
[INFO:root] Wrote 6 events to disk
```

**Comment by fhieber** [comment]
Thanks @reminisce, it's good to know that there is some I/O overhead with repeatedly constructing SummarWriters. Assuming that we would use a single SummarWriter instance during training, and flush it after every write, is there a risk of data loss if the training processes crashes at some point? Or would you recommend using a try-final block or ExitStack context to ensure closing of the SummaryWriter?

My original question was more around the logging statements done by mxboard. I am not very familiar with Python logging in general, but is there a way to disable the logging statements shown above?

**Comment by reminisce** [comment]
@fhieber 
Regarding closing the summary writer gracefully. Here is the analysis of several situations.
1. If you flush every time after calling `add_xxx`, there is almost no risk of data loss. However, this is not the recommended way of using the logger since `flush` would actually block the main thread till writing to the file finishes, while `add_xxx` only puts the item into the queue for logging, which is much faster than directly writing to files, and a separate thread would do the real logging work.
2. If some hard crash happens in the middle of training job without throwing any exceptions, for example, a segmentation fault caused by C++ code (probably caused by improper implementation), items in the queue for logging will be lost.
3. If some crash happens and raises an exception in Python, you would either need to wrap your code in the scope of `with SummaryWriter` or use a `try...except: sw.close()` block to prevent data loss. In the former case, you don't need to call `sw.close()` explicitly as the `with` statement would do that for you.

**Comment by fhieber** [comment]
Works, thanks!
